@baseUrl = http://152.53.132.106:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODE0ODgzOSwiZXhwIjoxNzY4MTQ5NzM5fQ.lXTxQzixcNULHJByGE76oUZqeShI1v_33En73h3zA4w
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODE0ODgzOSwiZXhwIjoxNzY4NzUzNjM5fQ.FBzHC3akUP0oRWu_eWu_heu5ehRg6_QB-PD7j_US3uA
@shortcode = VFQAP3
### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!",
  "displayName": "Test User"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}

### Get Me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### Update Me
PATCH {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "displayName": "Updated Name",
  "email": "newmail@example.com"
}

### Get Shortcode (Kurzcode + QR-Payload)
GET {{baseUrl}}/auth/shortcode
Authorization: Bearer {{accessToken}}

### Auth with Shortcode (liefert neue Tokens)
POST {{baseUrl}}/auth/shortcode
Content-Type: application/json

{
  "code": "{{shortcode}}"
}

### Delete Me
DELETE {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}